set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN T10 [get_ports {display_data[7]}]
set_property PACKAGE_PIN R10 [get_ports {display_data[6]}]
set_property PACKAGE_PIN K16 [get_ports {display_data[5]}]
set_property PACKAGE_PIN K13 [get_ports {display_data[4]}]
set_property PACKAGE_PIN P15 [get_ports {display_data[3]}]
set_property PACKAGE_PIN T11 [get_ports {display_data[2]}]
set_property PACKAGE_PIN L18 [get_ports {display_data[1]}]
set_property PACKAGE_PIN H15 [get_ports {display_data[0]}]
set_property PACKAGE_PIN U13 [get_ports {display_en[7]}]
set_property PACKAGE_PIN K2 [get_ports {display_en[6]}]
set_property PACKAGE_PIN T14 [get_ports {display_en[5]}]
set_property PACKAGE_PIN P14 [get_ports {display_en[4]}]
set_property PACKAGE_PIN J14 [get_ports {display_en[3]}]
set_property PACKAGE_PIN T9 [get_ports {display_en[2]}]
set_property PACKAGE_PIN J18 [get_ports {display_en[1]}]
set_property PACKAGE_PIN J17 [get_ports {display_en[0]}]

set_property PACKAGE_PIN M17 [get_ports {hardware_interrupt[2]}]
set_property PACKAGE_PIN N17 [get_ports {hardware_interrupt[1]}]
set_property PACKAGE_PIN P17 [get_ports {hardware_interrupt[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports {display_data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_en[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_en[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_en[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_en[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_en[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_en[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_en[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {display_en[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {hardware_interrupt[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {hardware_interrupt[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {hardware_interrupt[0]}]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
